#!/usr/bin/env bash
#
# Auto-fill deploy/customer.env from your Google Cloud + Workspace settings.
# It detects your account, project, domain, region and billing, asks which
# project to deploy into, and leaves only the SOCRadar feed key + company id
# for you to paste.
#
#   bash create-env.sh
#
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$HERE"                       # this script lives at the repo root
CFG="$ROOT/deploy/customer.env"

red(){   printf '\033[0;31m%s\033[0m\n' "$*"; }
green(){ printf '\033[0;32m%s\033[0m\n' "$*"; }
cyan(){  printf '\n\033[1;36m%s\033[0m\n' "$*"; }
GC="${GCLOUD:-gcloud}"

# Capture ONLY stderr of a gcloud call (stdout -> /dev/null), so we can detect a
# stale session without false-matching on success output (e.g. a project NAMED
# "Credentials Vault" must NOT look like an auth error).
gc_stderr(){ "$GC" "$@" 2>&1 1>/dev/null; }

# --- 0) signed in? ------------------------------------------------------------
ACCT="$($GC config get-value account 2>/dev/null || true)"
if [ -z "$ACCT" ] || [ "$ACCT" = "(unset)" ]; then
  red "You are not signed in to gcloud. Run:  gcloud auth login"; exit 1
fi

auth_err="$(gc_stderr projects list --limit=1 --format='value(projectId)' || true)"
if printf '%s' "$auth_err" | grep -qiE 'reauth|invalid_grant|auth tokens|unauthenticated|gcloud auth login'; then
  red "Your gcloud session needs a refresh. Run:  gcloud auth login   then run this again."; exit 1
fi

# domain from the account (guard against identities without '@')
case "$ACCT" in
  *@*) DOMAIN="${ACCT#*@}" ;;
  *)   DOMAIN=""; red "Could not derive a domain from '$ACCT' — you will need to set DOMAIN by hand." ;;
esac
green "Signed in as: $ACCT   (Workspace domain looks like: ${DOMAIN:-?})"

# --- 1) project: list, then pick (or auto if only one) ------------------------
PROJECTS=()
while IFS= read -r line || [ -n "$line" ]; do
  [ -n "$line" ] && PROJECTS+=("$line")
done < <($GC projects list --sort-by=projectId --format="value(projectId)" 2>/dev/null)

if [ "${#PROJECTS[@]}" -eq 0 ]; then
  red "No Google Cloud projects found on this account."
  echo "Create one first:  https://console.cloud.google.com/projectcreate"
  exit 1
fi

CUR="$($GC config get-value project 2>/dev/null || true)"; [ "$CUR" = "(unset)" ] && CUR=""

if [ "${#PROJECTS[@]}" -eq 1 ]; then
  PROJECT="${PROJECTS[0]}"
  echo "Using your only project: $PROJECT"
else
  cyan "Your projects:"
  def=""; i=1
  for p in "${PROJECTS[@]}"; do
    mark=""; if [ "$p" = "$CUR" ]; then mark="   (currently selected)"; def="$i"; fi
    printf "  %d) %s%s\n" "$i" "$p" "$mark"
    i=$((i+1))
  done
  printf "Pick the project to deploy into [1-%d] (Enter = %s): " "${#PROJECTS[@]}" "${def:-1}"
  pick=""
  read -r pick || true            # do NOT clobber on EOF: read still assigned pick
  [ -z "$pick" ] && pick="${def:-1}"
  case "$pick" in
    ''|*[!0-9]*) red "That is not a number. Re-run and pick 1-${#PROJECTS[@]}."; exit 1 ;;
  esac
  pick=$((10#$pick))              # force base-10 so '08'/'09' are not read as octal
  if [ "$pick" -lt 1 ] || [ "$pick" -gt "${#PROJECTS[@]}" ]; then
    red "Out of range. Re-run and pick 1-${#PROJECTS[@]}."; exit 1
  fi
  PROJECT="${PROJECTS[$((pick-1))]}"
fi
green "Project: $PROJECT"

# --- 2) billing (warn only; deploy needs it) ----------------------------------
EN="$($GC billing projects describe "$PROJECT" --format='value(billingEnabled)' 2>/dev/null || echo unknown)"
[ -n "$EN" ] || EN="unknown"
if [ "$EN" = "True" ]; then
  green "Billing: enabled"
else
  red "Billing on $PROJECT is '$EN'. Enable it before you deploy:"
  echo "  https://console.cloud.google.com/billing/enable?project=$PROJECT"
fi

# --- 3) idempotency: do not clobber an existing config without asking ----------
if [ -f "$CFG" ]; then
  printf "deploy/customer.env already exists. Overwrite it? [y/N]: "
  yn=""
  read -r yn || true
  case "$yn" in
    y|Y|yes|YES) : ;;
    *) echo "Kept your existing deploy/customer.env. Edit it directly, or delete it and re-run."; exit 0 ;;
  esac
fi

# --- 4) write the pre-filled config -------------------------------------------
STAMP="$(date '+%Y-%m-%d %H:%M' 2>/dev/null || echo)"
mkdir -p "$ROOT/deploy"
cat > "$CFG" <<EOF
# Auto-generated by create-env.sh ($STAMP). Detected values are filled in.
# You only need to add your SOCRadar FEED_API_KEY + FEED_COMPANY_ID below, then run:
#     bash setup.sh
# This file is git-ignored, so your secrets never commit.

PROJECT=$PROJECT
REGION=europe-west1
DOMAIN=$DOMAIN

# ADMIN_SUBJECT = the admin the connector impersonates on every call.
# Defaulted to YOU ($ACCT) so a quick test works out of the box (this account exists
# and you can authorize it). For PRODUCTION switch to a DEDICATED least-privilege admin,
# e.g. connector-bot@$DOMAIN, created with the 7-privilege custom role in
# docs/deploy-to-gcp-guide.md. Whatever you set here MUST be a real, existing admin.
ADMIN_SUBJECT=$ACCT
CUSTOMER_ID=my_customer

# ---- the ONLY two values you must paste yourself (from SOCRadar) ----
FEED_API_KEY=
FEED_COMPANY_ID=
# --------------------------------------------------------------------
FEED_BASE=https://platform.socradar.com

# Admin-UI sign-in: native Cloud Run IAP — NO OAuth client needed. Just run 'bash enable-iap.sh' after deploy.
USE_IAP=true
# OAuth is ONLY for USE_IAP=false (the local-machine proxy path, open-panel.sh). To use it instead of IAP:
# set USE_IAP=false, create a Web OAuth client (redirect http://localhost:8080/auth/callback), then
# uncomment the next two lines and paste the id + secret:
#GOOGLE_CLIENT_ID=
#GOOGLE_CLIENT_SECRET=

DEPLOY_MODE=service
# Durable storage. firestore (recommended, default) = audit log + flagged users + scan history SURVIVE
# restart/scale-to-zero; setup.sh auto-creates the database for you. sqlite = in-memory /tmp, resets when the
# service goes idle — fine only for a throwaway demo.
STORAGE_BACKEND=firestore
EOF

if [ ! -s "$CFG" ]; then
  red "Could not write $CFG  (does deploy/ exist and is it writable?)"; exit 1
fi

green "Wrote deploy/customer.env with your detected settings."
cyan "Next steps"
cat <<EOF
  1. Open deploy/customer.env and paste your SOCRadar FEED_API_KEY + FEED_COMPANY_ID. Save.
     ADMIN_SUBJECT is set to you ($ACCT) for a quick test; switch it to a dedicated
     least-privilege admin for production. It must be a real, existing admin either way.
  2. Sign-in is native IAP by default (USE_IAP=true) — no OAuth client to create. Just run setup.sh,
     then enable-iap.sh. (Leave GOOGLE_CLIENT_ID/SECRET empty.)
  3. Run:  bash setup.sh    to validate and deploy, then  bash enable-iap.sh  to turn on IAP.
EOF

# In Cloud Shell, open the file in the editor for the customer.
command -v cloudshell >/dev/null 2>&1 && cloudshell edit "$CFG" 2>/dev/null || true
